# jekyll config
# _drafts blog
# theme partly based on: 
# Kiko-plus https://aweekj.github.io/Kiko-plus/ and Minima https://github.com/jekyll/minima

# basic
title: sveska
description: a blog of learning things.
keywords: cerificate
author: acailic
github_username: acailic

url: https://acailic.github.io
baseurl: /sveska

# build
collections:
  notes:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
